export default {
  icon: {
    arrowleft: "arrow-left",
    atom:"atom",
    bell:"bell",
    calendarcheck:"calendar-check",
    calendarrange: "calendar-range",
    circle: "circle",
    circlecheck: "circle-check",
    code: "code",
    copyright: "copyright",
    database: "database",
    diced6: "dice-d6",
    diced20: "dice-d20",
    download: "download",
    ellipsis: "ellipsis",
    filter: "filter",
    gear: "gear",
    gem: "gem",
    globe: "globe",
    heart: "heart",
    image: "image",
    images: "images",
    language: "language",
    layergroup: "layer-group",
    list: "list",
    listcheck: "list-check",
    magnifyingglass: "magnifying-glass",
    moonstars: "moon-stars",
    networkwired: "network-wired",
    palette: "palette",
    paperclip: "paperclip",
    paperplane: "paper-plane",
    plug: "plug",
    plus: "plus",
    section: "section",
    sharenodes: "share-nodes",
    star: "star",
    sunbright: "sun-bright",
    swatchbook: "swatchbook",
    thumbsup: "thumbs-up",
    timer: "timer",
    trash: "trash",
    user: "user",
    userplus: "user-plus",
    xmark: "xmark",
  }
}