// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Category: typeof import('./src/section/Category.vue')['default']
    Date: typeof import('./src/section/Date.vue')['default']
    Footer: typeof import('./src/section/layout/Footer.vue')['default']
    Header: typeof import('./src/section/layout/Header.vue')['default']
    Link: typeof import('./src/section/Link.vue')['default']
    LocaleSwitcher: typeof import('./src/section/LocaleSwitcher.vue')['default']
    Logo: typeof import('./src/section/Logo.vue')['default']
    MobileMenu: typeof import('./src/section/MobileMenu.vue')['default']
    PageBreadcrumb: typeof import('./src/section/PageBreadcrumb.vue')['default']
    PageBreadcrumbItem: typeof import('./src/section/PageBreadcrumbItem.vue')['default']
    PageSubtitle: typeof import('./src/section/PageSubtitle.vue')['default']
    PageTitle: typeof import('./src/section/PageTitle.vue')['default']
    Post: typeof import('./src/section/Post.vue')['default']
    PostItem: typeof import('./src/section/PostItem.vue')['default']
    PostList: typeof import('./src/section/PostList.vue')['default']
    ProjectCard: typeof import('./src/section/ProjectCard.vue')['default']
    ProjectList: typeof import('./src/section/ProjectList.vue')['default']
    ProjectSearch: typeof import('./src/section/ProjectSearch.vue')['default']
    README: typeof import('./src/section/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/section/Search.vue')['default']
    SectionContainer: typeof import('./src/section/SectionContainer.vue')['default']
    Sidebar: typeof import('./src/section/layout/Sidebar.vue')['default']
    SocialIcon: typeof import('./src/section/SocialIcon.vue')['default']
    Tag: typeof import('./src/section/Tag.vue')['default']
    Technology: typeof import('./src/section/Technology.vue')['default']
    ThemeSwitcher: typeof import('./src/section/ThemeSwitcher.vue')['default']
    Toc: typeof import('./src/section/Toc.vue')['default']
    TocItem: typeof import('./src/section/TocItem.vue')['default']
    TwBadge: typeof import('./src/section/TwBadge.vue')['default']
    TwDismissableBadge: typeof import('./src/section/TwDismissableBadge.vue')['default']
  }
}
