// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Basic: typeof import('./src/pecket/Element/Button/demo/Basic.vue')['default']
    Footer: typeof import('./src/section/layout/Footer.vue')['default']
    Header: typeof import('./src/section/layout/Header.vue')['default']
    HeaderLink: typeof import('./src/section/HeaderLink.vue')['default']
    Link: typeof import('./src/section/markdown/Link.vue')['default']
    Post: typeof import('./src/section/markdown/Post.vue')['default']
    PostItem: typeof import('./src/section/PostItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/section/layout/Sidebar.vue')['default']
    ThemeSelect: typeof import('./src/section/ThemeSelect.vue')['default']
    Toc: typeof import('./src/section/markdown/Toc.vue')['default']
    TocItem: typeof import('./src/section/markdown/TocItem.vue')['default']
  }
}
