export default {
  '.btn-xs': {
    height: '2rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
  },
  '.btn-xs.btn-circle': {
    borderRadius: '9999px',
    padding: '0px !important',
    width: '2rem',
  },
  '.btn-xs .icon-loading': {
    height: '0.75rem',
    marginRight: '0.25rem',
    width: '0.75rem',
  },
  '.btn-sm': {
    height: '2.5rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
  },
  '.btn-sm.btn-circle': {
    borderRadius: '9999px',
    padding: '0px !important',
    width: '2.5rem',
  },
  '.btn-sm .icon-loading': {
    height: '1rem',
    marginRight: '0.5rem',
    width: '1rem',
  },
  '.btn-md': {
    height: '3rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
  },
  '.btn-md.btn-circle': {
    borderRadius: '9999px',
    padding: '0px !important',
    width: '3rem',
  },
  '.btn-md .icon-loading': {
    height: '1.25rem',
    marginLeft: '-0.25rem',
    marginRight: '0.5rem',
    width: '1.25rem',
  },
  '.btn-lg': {
    height: '3.5rem',
    fontSize: '1rem',
    lineHeight: '1.5rem',
    paddingLeft: '1.25rem',
    paddingRight: '1.25rem',
  },
  '.btn-lg.btn-circle': {
    borderRadius: '9999px',
    padding: '0px !important',
    width: '3.5rem',
  },
  '.btn-lg .icon-loading': {
    height: '1.5rem',
    marginLeft: '-0.25rem',
    marginRight: '0.75rem',
    width: '1.5rem',
  },
  '.btn-xl': {
    height: '4rem',
    fontSize: '1.25rem',
    lineHeight: '1.75rem',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
  },
  '.btn-xl.btn-circle': {
    borderRadius: '9999px',
    padding: '0px !important',
    width: '4rem',
  },
  '.btn-xl .icon-loading': {
    height: '1.75rem',
    marginLeft: '-0.25rem',
    marginRight: '0.75rem',
    width: '1.75rem',
  },
}
